fix: Add encoding='utf-8' to RotatingFileHandler.
Otherwise the logging fails by spamming the uWSGI error log (stderr):

    --- Logging error ---
    Traceback (most recent call last):
      File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
        stream.write(msg)
    UnicodeEncodeError: 'ascii' codec can't encode character '\xe9'
      in position 305: ordinal not in range(128)
    Call stack:
    ...
      File "slackbridge.py", line 329, in respond
        self.log.info('Responding with %r to %s', payload, config['iwh_url'])
    Unable to print the message and arguments - possible formatting error.
    Use the traceback above to help find the error.

Note that no messages were lost, only missing entries in the log.